/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.UI;

import com.inventory.DAO.CustomerDAO;
import com.inventory.DTO.CustomerDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author GKV
 */
public class CustomersPage extends javax.swing.JPanel {

    /**
     * Creates new form Products
     */
    private CustomerDAO customerDAO;
    private boolean isEditMode = false;
    private String originalCustomerCode = null;
    
    public CustomersPage() {
        initComponents();
        customerDAO = new CustomerDAO();
        loadCustomersData();
        setupSearch();
        customizeTable();
        clearForm();
        updateButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        brandLabe = new javax.swing.JPanel();
        codeLabel = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        locationText = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        debitAmountText = new javax.swing.JTextField();
        debitAmountLabel = new javax.swing.JLabel();
        creditAmountText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        creditAmountLabel = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1118, 616));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("CUSTOMERS");

        custTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        custTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(custTable);

        brandLabe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

        codeLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        codeLabel.setText("Customer Code:");

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Full Name:");

        locationLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        locationLabel.setText("Location:");

        contactLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contactLabel.setText("Contact#:");

        debitAmountLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        debitAmountLabel.setText("Debit Amount:");

        addButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(this::addButtonActionPerformed);

        creditAmountLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        creditAmountLabel.setText("Credit Amount:");

        delButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        delButton.setText("Delete");
        delButton.addActionListener(this::delButtonActionPerformed);

        updateButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        clearButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        javax.swing.GroupLayout brandLabeLayout = new javax.swing.GroupLayout(brandLabe);
        brandLabe.setLayout(brandLabeLayout);
        brandLabeLayout.setHorizontalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText)
                            .addComponent(codeText)))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(debitAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debitAmountText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(creditAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditAmountText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        brandLabeLayout.setVerticalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codeText)
                    .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debitAmountLabel)
                    .addComponent(debitAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditAmountLabel)
                    .addComponent(creditAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        searchLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchLabel.setText("Search: ");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(searchLabel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchField))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custTableMouseClicked
        int row = custTable.getSelectedRow();
        if (row >= 0) {
            originalCustomerCode = custTable.getValueAt(row, 0).toString();
            codeText.setText(originalCustomerCode);
            codeText.setEnabled(true);
            nameText.setText(custTable.getValueAt(row, 1).toString());
            locationText.setText(custTable.getValueAt(row, 2).toString());
            contactText.setText(custTable.getValueAt(row, 3).toString());

            // Load debit and credit from database (they are not in the visible table)
            loadCustomerFinancialData(originalCustomerCode);

            isEditMode = true;
            updateButton.setEnabled(true);
        }
    }//GEN-LAST:event_custTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addCustomer();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateCustomer();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_delButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Load customers data into table
    public void loadCustomersData() {
        try {
        ResultSet rs = customerDAO.getQueryResult();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"CUSTOMER CODE", "FULL NAME", "LOCATION", "CONTACT"});
        
        if (rs != null) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("customercode"),
                    rs.getString("fullname"),
                    rs.getString("location"),
                    rs.getString("phone")
                });
            }
            rs.close();
        }
        custTable.setModel(model);
        
        if (model.getRowCount() > 0) {
            customizeTable();
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading customers: " + ex.getMessage());
    }
    }
    
    // Search customers
    private void searchCustomers() {
    String searchText = searchField.getText().trim();
    
    if (searchText.isEmpty()) {
        loadCustomersData();
    } else {
        try {
            ResultSet rs = customerDAO.getCustomerSearch(searchText);
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"CUSTOMER CODE", "FULL NAME", "LOCATION", "CONTACT"});
            
            if (rs != null) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("customercode"),
                        rs.getString("fullname"),
                        rs.getString("location"),
                        rs.getString("phone")
                    });
                }
                rs.close();
            }
            custTable.setModel(model);
            
            if (model.getRowCount() > 0) {
                customizeTable();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error searching customers: " + ex.getMessage());
        }
    }
}
    
    // Setup search functionality
    private void setupSearch() {
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchCustomers();
            }
        });
    }
    
    // Clear form fields
    public void clearForm() {
        codeText.setText("");
        nameText.setText("");
        locationText.setText("");
        contactText.setText("");
        debitAmountText.setText("");
        creditAmountText.setText("");
        
        isEditMode = false;
        originalCustomerCode = null;
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        codeText.setEnabled(true);
        custTable.clearSelection();
    }
    
    // Customize table appearance
    private void customizeTable() {
    try {
        if (custTable.getColumnCount() == 0) return;
        
        custTable.getColumnModel().getColumn(0).setPreferredWidth(100);  // Code
        custTable.getColumnModel().getColumn(1).setPreferredWidth(200);  // Name
        custTable.getColumnModel().getColumn(2).setPreferredWidth(150);  // Location
        custTable.getColumnModel().getColumn(3).setPreferredWidth(120);  // Contact
        
        custTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        custTable.setRowHeight(25);
        
        JTableHeader header = custTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 12));
        header.setBackground(new Color(240, 240, 240));
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    // Add new customer
    private void addCustomer() {
        if (codeText.getText().trim().isEmpty() ||
            nameText.getText().trim().isEmpty() ||
            locationText.getText().trim().isEmpty() ||
            contactText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all required fields (Code, Name, Location, Contact).");
            return;
        }
        
        try {
            CustomerDTO customerDTO = new CustomerDTO();
            customerDTO.setCustCode(codeText.getText().trim().toUpperCase());
            customerDTO.setFullName(nameText.getText().trim());
            customerDTO.setLocation(locationText.getText().trim());
            customerDTO.setPhone(contactText.getText().trim());
            
            double debit = 0.0;
            double credit = 0.0;
            if (!debitAmountText.getText().trim().isEmpty()) {
                debit = Double.parseDouble(debitAmountText.getText().trim());
            }
            if (!creditAmountText.getText().trim().isEmpty()) {
                credit = Double.parseDouble(creditAmountText.getText().trim());
            }
            customerDTO.setDebit(debit);
            customerDTO.setCredit(credit);
            customerDTO.setBalance(credit - debit);
            
            customerDAO.addCustomerDAO(customerDTO);
            loadCustomersData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Customer added successfully!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Debit and Credit amounts.");
        }
    }
    
    // Update existing customer
    private void updateCustomer() {
        if (originalCustomerCode == null) {
            JOptionPane.showMessageDialog(null, "No customer selected for update.");
            return;
        }
        
        if (nameText.getText().trim().isEmpty() ||
            locationText.getText().trim().isEmpty() ||
            contactText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all required fields.");
            return;
        }
        
        try {
            String newCustomerCode = codeText.getText().trim().toUpperCase();
            String oldCustomerCode = originalCustomerCode;
            
            CustomerDTO customerDTO = new CustomerDTO();
            customerDTO.setCustCode(newCustomerCode);
            customerDTO.setFullName(nameText.getText().trim());
            customerDTO.setLocation(locationText.getText().trim());
            customerDTO.setPhone(contactText.getText().trim());
            
            double debit = 0.0;
            double credit = 0.0;
            if (!debitAmountText.getText().trim().isEmpty()) {
                debit = Double.parseDouble(debitAmountText.getText().trim());
            }
            if (!creditAmountText.getText().trim().isEmpty()) {
                credit = Double.parseDouble(creditAmountText.getText().trim());
            }
            customerDTO.setDebit(debit);
            customerDTO.setCredit(credit);
            customerDTO.setBalance(credit - debit);
            
            // If customer code changed, update everything
            if (!newCustomerCode.equals(oldCustomerCode)) {
                customerDAO.updateCustomerWithCodeChange(customerDTO, oldCustomerCode);
            } else {
                customerDAO.editCustomerDAO(customerDTO);
            }
            
            loadCustomersData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Customer updated successfully!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Debit and Credit amounts.");
        }
    }
    
    // Delete customer
    private void deleteCustomer() {
        int selectedRow = custTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a customer to delete.");
            return;
        }
        
        String customerCode = custTable.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete customer: " + customerCode + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            customerDAO.deleteCustomerDAO(customerCode);
            loadCustomersData();
            clearForm();
        }
    }
    
    // Refresh data
    private void refreshData() {
        loadCustomersData();
        clearForm();
        JOptionPane.showMessageDialog(null, "Data refreshed!");
    }
    
    // Refresh page data (called from Dashboard)
    public void refreshPageData() {
        loadCustomersData();
        clearForm();
        System.out.println("Customers page data refreshed");
    }
    
    // Helper method to load financial data for editing
    private void loadCustomerFinancialData(String customerCode) {
        try {
            ResultSet rs = customerDAO.getCustomerByCode(customerCode);
            if (rs != null && rs.next()) {
                debitAmountText.setText(String.format("%.2f", rs.getDouble("debit")));
                creditAmountText.setText(String.format("%.2f", rs.getDouble("credit")));
                rs.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel brandLabe;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeText;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactText;
    private javax.swing.JLabel creditAmountLabel;
    private javax.swing.JTextField creditAmountText;
    private javax.swing.JTable custTable;
    private javax.swing.JLabel debitAmountLabel;
    private javax.swing.JTextField debitAmountText;
    private javax.swing.JButton delButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
