/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.UI;

import com.inventory.DAO.ProductDAO;
import com.inventory.DAO.SupplierDAO;
import com.inventory.DTO.ProductDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author GKV
 */
public class ProductsPage extends javax.swing.JPanel {

    /**
     * Creates new form Products
     */
    private ProductDAO productDAO;
    private SupplierDAO supplierDAO;
    private boolean isEditMode = false;
    private String originalProductCode = null;
    
    public ProductsPage() {
        initComponents();
        productDAO = new ProductDAO();
        supplierDAO = new SupplierDAO();
        loadSuppliersToCombo();
        loadProductsData();
        setupSearch();
        customizeTable();
        clearForm();
        
        
        // only enable when editing
        updateButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        brandLabe = new javax.swing.JPanel();
        suppCombo = new javax.swing.JComboBox<>();
        btnAddSupp = new javax.swing.JButton();
        codeLabel = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        quantityText = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        costText = new javax.swing.JTextField();
        costLabel = new javax.swing.JLabel();
        sellText = new javax.swing.JTextField();
        sellLabel = new javax.swing.JLabel();
        brandText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        codeLabel6 = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1118, 616));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTS");

        productsTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productsTable);

        brandLabe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Product Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

        suppCombo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        suppCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a supplier" }));

        btnAddSupp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAddSupp.setText("Click to add a New Supplier");
        btnAddSupp.addActionListener(this::btnAddSuppActionPerformed);

        codeLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        codeLabel.setText("Product Code:");

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Product Name:");

        dateLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dateLabel.setText("Date:");

        quantityLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        quantityLabel.setText("Quantity:");

        costLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        costLabel.setText("Cost Price:");

        sellLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        sellLabel.setText("Selling Price:");

        addButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(this::addButtonActionPerformed);

        codeLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        codeLabel6.setText("Brand:");

        delButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        delButton.setText("Delete");
        delButton.addActionListener(this::delButtonActionPerformed);

        updateButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        clearButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        javax.swing.GroupLayout brandLabeLayout = new javax.swing.GroupLayout(brandLabe);
        brandLabe.setLayout(brandLabeLayout);
        brandLabeLayout.setHorizontalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText)
                            .addComponent(codeText)))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(sellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(codeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        brandLabeLayout.setVerticalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suppCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codeText)
                    .addComponent(codeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellLabel)
                    .addComponent(sellText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel6)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        searchLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchLabel.setText("Search: ");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(searchLabel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchField))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuppActionPerformed
        // Get the parent Dashboard instance
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        if (dashboard != null) {
            dashboard.addSuppPage();  // Call Dashboard's method to show supplier page
        } else {
            JOptionPane.showMessageDialog(null, "Cannot navigate to Suppliers page.");
        }
    }//GEN-LAST:event_btnAddSuppActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addProduct();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateProduct();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        deleteProduct();
    }//GEN-LAST:event_delButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void productsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsTableMouseClicked
        int row = productsTable.getSelectedRow();
        if (row >= 0) {
            originalProductCode = productsTable.getValueAt(row, 0).toString();
            codeText.setText(originalProductCode);
            codeText.setEnabled(true);  // KEEP ENABLED - allow editing
            nameText.setText(productsTable.getValueAt(row, 1).toString());
            costText.setText(productsTable.getValueAt(row, 2).toString());
            sellText.setText(productsTable.getValueAt(row, 3).toString());
            brandText.setText(productsTable.getValueAt(row, 4).toString());

            isEditMode = true;
            updateButton.setEnabled(true);
            // Add button stays enabled
        }
    }//GEN-LAST:event_productsTableMouseClicked
    
    // Load suppliers into combo box
    public void loadSuppliersToCombo() {
        try {
            ResultSet rs = supplierDAO.getSuppliersForCombo();
            suppCombo.removeAllItems();
            suppCombo.addItem("-- Select Supplier --");
            while (rs.next()) {
                suppCombo.addItem(rs.getString("fullname"));
            }
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    // Load products data into table
    public void loadProductsData() {
        try {
            ResultSet rs = productDAO.getQueryResult();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"PRODUCT CODE", "PRODUCT NAME", "COST PRICE", "SELL PRICE", "BRAND"});
            
            if (rs != null) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("productcode"),
                        rs.getString("productname"),
                        String.format("%.2f", rs.getDouble("costprice")),
                        String.format("%.2f", rs.getDouble("sellprice")),
                        rs.getString("brand")
                    });
                }
                rs.close();
            }
            productsTable.setModel(model);
            
            if (model.getRowCount() > 0) {
                customizeTable();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading products: " + ex.getMessage());
        }
    }
    
    // Search products
    private void searchProducts() {
        String searchText = searchField.getText().trim();
        
        if (searchText.isEmpty()) {
            loadProductsData();
        } else {
            try {
                ResultSet rs = productDAO.getProductSearch(searchText);
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new String[]{"PRODUCT CODE", "PRODUCT NAME", "COST PRICE", "SELL PRICE", "BRAND"});
                
                if (rs != null) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getString("productcode"),
                            rs.getString("productname"),
                            String.format("%.2f", rs.getDouble("costprice")),
                            String.format("%.2f", rs.getDouble("sellprice")),
                            rs.getString("brand")
                        });
                    }
                    rs.close();
                }
                productsTable.setModel(model);
                
                if (model.getRowCount() > 0) {
                    customizeTable();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error searching products: " + ex.getMessage());
            }
        }
    }
    
    // Setup search functionality
    private void setupSearch() {
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchProducts();
            }
        });
    }
    
    // Clear form fields
    public void clearForm() {
        codeText.setText("");
        nameText.setText("");
        costText.setText("");
        sellText.setText("");
        brandText.setText("");
        quantityText.setText("");
        suppCombo.setSelectedIndex(0);
        jDateChooser1.setDate(new Date());

        isEditMode = false;
        originalProductCode = null;
        updateButton.setEnabled(false);
        codeText.setEnabled(true);  // Keep enabled
        productsTable.clearSelection();
    }
    
    // Customize table appearance
    private void customizeTable() {
        try {
            if (productsTable.getColumnCount() == 0) return;
            
            productsTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            productsTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            productsTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            productsTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            productsTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
            productsTable.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
            productsTable.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            
            productsTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            productsTable.setRowHeight(25);
            
            JTableHeader header = productsTable.getTableHeader();
            header.setFont(new Font("Segoe UI", Font.BOLD, 12));
            header.setBackground(new Color(240, 240, 240));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Add new product
    private void addProduct() {
        if (codeText.getText().trim().isEmpty() ||
            nameText.getText().trim().isEmpty() ||
            costText.getText().trim().isEmpty() ||
            sellText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all required fields.");
            return;
        }

        try {
            ProductDTO productDTO = new ProductDTO();
            productDTO.setProdCode(codeText.getText().trim().toUpperCase());
            productDTO.setProdName(nameText.getText().trim());
            productDTO.setCostPrice(Double.parseDouble(costText.getText().trim()));
            productDTO.setSellPrice(Double.parseDouble(sellText.getText().trim()));
            productDTO.setBrand(brandText.getText().trim());

            int quantity = 0;
            if (!quantityText.getText().trim().isEmpty()) {
                quantity = Integer.parseInt(quantityText.getText().trim());
            }
            productDTO.setQuantity(quantity);

            productDAO.addProductDAO(productDTO);  // Call the DAO method
            loadProductsData();
            clearForm();

            // Refresh the Current Stock page
            refreshCurrentStockPage();

            JOptionPane.showMessageDialog(null, "Product added successfully!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for price and quantity.");
        }
    }

    
    // Update existing product
    private void updateProduct() {
            if (nameText.getText().trim().isEmpty() ||
            costText.getText().trim().isEmpty() ||
            sellText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all required fields.");
            return;
        }

        try {
            String newProductCode = codeText.getText().trim().toUpperCase();
            String oldProductCode = originalProductCode;

            ProductDTO productDTO = new ProductDTO();
            productDTO.setProdCode(newProductCode);
            productDTO.setProdName(nameText.getText().trim());
            productDTO.setCostPrice(Double.parseDouble(costText.getText().trim()));
            productDTO.setSellPrice(Double.parseDouble(sellText.getText().trim()));
            productDTO.setBrand(brandText.getText().trim());

            // If product code changed, update everything
            if (!newProductCode.equals(oldProductCode)) {
                productDAO.updateProductWithCodeChange(productDTO, oldProductCode);
            } else {
                productDAO.editProdDAO(productDTO);
            }

            loadProductsData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Product updated successfully!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for price.");
        }
    }
    
    // Delete product
    private void deleteProduct() {
        int selectedRow = productsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a product to delete.");
            return;
        }
        
        String productCode = productsTable.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete product: " + productCode + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            productDAO.deleteProductDAO(productCode);
            loadProductsData();
            clearForm();
        }
    }
    
    // Refresh button action
    private void refreshData() {
        loadSuppliersToCombo();
        loadProductsData();
        clearForm();
        JOptionPane.showMessageDialog(null, "Data refreshed!");
    }
    
    private void refreshCurrentStockPage() {
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        if (dashboard != null) {
            dashboard.refreshCurrentStock();
        }
    }
    
    public void refreshPageData() {
        loadSuppliersToCombo();
        loadProductsData();
        clearForm();
        System.out.println("Products page data refreshed");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel brandLabe;
    private javax.swing.JTextField brandText;
    private javax.swing.JButton btnAddSupp;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel codeLabel6;
    private javax.swing.JTextField codeText;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costText;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JTable productsTable;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityText;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel sellLabel;
    private javax.swing.JTextField sellText;
    private javax.swing.JComboBox<String> suppCombo;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
