/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.UI;

import com.inventory.DAO.ProductDAO;
import com.inventory.DAO.SupplierDAO;
import com.inventory.DTO.ProductDTO;
import com.inventory.DTO.SupplierDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author GKV
 */
public class PurchasePage extends javax.swing.JPanel {

    /**
     * Creates new form Products
     */
    private ProductDAO productDAO;
    private SupplierDAO supplierDAO;
    private boolean isEditMode = false;
    private int originalPurchaseID = -1;
    
    public PurchasePage() {
        initComponents();
        productDAO = new ProductDAO();
        supplierDAO = new SupplierDAO();
        loadSuppliersToCombo();
        loadPurchaseData();
        setupSearch();
        customizeTable();
        clearForm();
        updateButton.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseTable = new javax.swing.JTable();
        brandLabe = new javax.swing.JPanel();
        suppCombo = new javax.swing.JComboBox<>();
        btnAddSupp = new javax.swing.JButton();
        codeLabel = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        quantityText = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        costText = new javax.swing.JTextField();
        costLabel = new javax.swing.JLabel();
        sellText = new javax.swing.JTextField();
        sellLabel = new javax.swing.JLabel();
        brandText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        codeLabel6 = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1118, 616));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("PURCHASE");

        purchaseTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        purchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        purchaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchaseTable);

        brandLabe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Purchase Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

        suppCombo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        suppCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a supplier" }));

        btnAddSupp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAddSupp.setText("Click to add a New Supplier");

        codeLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        codeLabel.setText("Product Code:");

        codeText.addActionListener(this::codeTextActionPerformed);
        codeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeTextKeyReleased(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Product Name:");

        dateLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dateLabel.setText("Date:");

        quantityLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        quantityLabel.setText("Quantity:");

        costLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        costLabel.setText("Cost Price:");

        sellLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        sellLabel.setText("Selling Price:");

        addButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(this::addButtonActionPerformed);

        codeLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        codeLabel6.setText("Brand:");

        delButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        delButton.setText("Delete");
        delButton.addActionListener(this::delButtonActionPerformed);

        updateButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        clearButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        javax.swing.GroupLayout brandLabeLayout = new javax.swing.GroupLayout(brandLabe);
        brandLabe.setLayout(brandLabeLayout);
        brandLabeLayout.setHorizontalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText)
                            .addComponent(codeText)))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(costLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(sellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(codeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        brandLabeLayout.setVerticalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suppCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codeText)
                    .addComponent(codeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellLabel)
                    .addComponent(sellText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel6)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        searchLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchLabel.setText("Search: ");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(searchLabel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchField))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addPurchase();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updatePurchase();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        deletePurchase();
    }//GEN-LAST:event_delButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void purchaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseTableMouseClicked
        int row = purchaseTable.getSelectedRow();
        if (row >= 0) {
            originalPurchaseID = (int) purchaseTable.getValueAt(row, 0);
            String productCode = purchaseTable.getValueAt(row, 1).toString();
            
            codeText.setText(productCode);
            codeText.setEnabled(false);
            loadProductDetails();
            
            // Load the full purchase details from database
            loadPurchaseDetails(originalPurchaseID);
            
            isEditMode = true;
            updateButton.setEnabled(true);
            addButton.setEnabled(true);
        }
    }//GEN-LAST:event_purchaseTableMouseClicked

    private void codeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeTextKeyReleased
        
    }//GEN-LAST:event_codeTextKeyReleased

    private void codeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTextActionPerformed
        loadProductDetails();
    }//GEN-LAST:event_codeTextActionPerformed

    // Load product details automatically when product code is entered
    private void loadProductDetails() {
        String productCode = codeText.getText().trim();
        if (!productCode.isEmpty()) {
            try {
                ResultSet rs = productDAO.getProdFromCode(productCode);
                if (rs != null && rs.next()) {
                    nameText.setText(rs.getString("productname"));
                    costText.setText(String.format("%.2f", rs.getDouble("costprice")));
                    sellText.setText(String.format("%.2f", rs.getDouble("sellprice")));
                    brandText.setText(rs.getString("brand"));
                    
                    // Auto-calculate total cost if quantity is already entered
                    calculateTotalCost();
                    rs.close();
                } else {
                    // Clear fields if product not found
                    nameText.setText("");
                    costText.setText("");
                    sellText.setText("");
                    brandText.setText("");
                    JOptionPane.showMessageDialog(null, "Product not found. Please check the product code.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            // Clear fields if product code is empty
            nameText.setText("");
            costText.setText("");
            sellText.setText("");
            brandText.setText("");
        }
    }
    
    // Calculate and display total cost
    private void calculateTotalCost() {
        try {
            int quantity = 0;
            double costPrice = 0;
            
            if (!quantityText.getText().trim().isEmpty()) {
                quantity = Integer.parseInt(quantityText.getText().trim());
            }
            if (!costText.getText().trim().isEmpty()) {
                costPrice = Double.parseDouble(costText.getText().trim());
            }
            
            double totalCost = quantity * costPrice;
            // Display total cost in a label if you have one, or store for later use
            System.out.println("Total Cost: " + totalCost);
            
            // If you have a totalCostLabel, uncomment:
            // totalCostLabel.setText(String.format("Total Cost: %.2f", totalCost));
        } catch (NumberFormatException e) {
            // Ignore invalid input
        }
    }
    
    // Load purchase data into table
    public void loadPurchaseData() {
        try {
            ResultSet rs = productDAO.getPurchaseInfo();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"PURCHASE ID", "PRODUCT CODE", "PRODUCT NAME", "QUANTITY", "TOTAL COST"});
            
            if (rs != null) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("purchaseID"),
                        rs.getString("productcode"),
                        rs.getString("productname"),
                        rs.getInt("quantity"),
                        String.format("%.2f", rs.getDouble("totalcost"))
                    });
                }
                rs.close();
            }
            purchaseTable.setModel(model);
            
            if (model.getRowCount() > 0) {
                customizeTable();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading purchase data: " + ex.getMessage());
        }
    }
    
    // Search purchase records
    private void searchPurchase() {
        String searchText = searchField.getText().trim();
        
        if (searchText.isEmpty()) {
            loadPurchaseData();
        } else {
            try {
                ResultSet rs = productDAO.getPurchaseSearch(searchText);
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new String[]{"PURCHASE ID", "PRODUCT CODE", "PRODUCT NAME", "QUANTITY", "TOTAL COST"});
                
                if (rs != null) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getInt("purchaseID"),
                            rs.getString("productcode"),
                            rs.getString("productname"),
                            rs.getInt("quantity"),
                            String.format("%.2f", rs.getDouble("totalcost"))
                        });
                    }
                    rs.close();
                }
                purchaseTable.setModel(model);
                
                if (model.getRowCount() > 0) {
                    customizeTable();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error searching purchase: " + ex.getMessage());
            }
        }
    }
    
    // Setup search functionality
    private void setupSearch() {
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchPurchase();
            }
        });
    }
    
    // Clear form fields
    public void clearForm() {
        suppCombo.setSelectedIndex(0);
        codeText.setText("");
        nameText.setText("");
        jDateChooser1.setDate(new Date());
        quantityText.setText("");
        costText.setText("");
        sellText.setText("");
        brandText.setText("");
        
        isEditMode = false;
        originalPurchaseID = -1;
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        codeText.setEnabled(true);
        purchaseTable.clearSelection();
    }
    
    // Customize table appearance
    private void customizeTable() {
        try {
            if (purchaseTable.getColumnCount() == 0) return;
            
            purchaseTable.getColumnModel().getColumn(0).setPreferredWidth(80);   // ID
            purchaseTable.getColumnModel().getColumn(1).setPreferredWidth(100);  // Product Code
            purchaseTable.getColumnModel().getColumn(2).setPreferredWidth(200);  // Product Name
            purchaseTable.getColumnModel().getColumn(3).setPreferredWidth(80);   // Quantity
            purchaseTable.getColumnModel().getColumn(4).setPreferredWidth(100);  // Total Cost
            
            // Center align quantity
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            purchaseTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
            
            // Right align total cost
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
            purchaseTable.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            
            purchaseTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            purchaseTable.setRowHeight(25);
            
            JTableHeader header = purchaseTable.getTableHeader();
            header.setFont(new Font("Segoe UI", Font.BOLD, 12));
            header.setBackground(new Color(240, 240, 240));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Add new purchase transaction
    private void addPurchase() {
        if (suppCombo.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Please select a supplier.");
            return;
        }
        if (codeText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product Code.");
            return;
        }
        if (quantityText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Quantity.");
            return;
        }
        if (costText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cost price not found for this product.");
            return;
        }
        
        try {
            // Get selected supplier code
            String selectedSupplier = suppCombo.getSelectedItem().toString();
            String supplierCode = selectedSupplier.substring(selectedSupplier.indexOf("(") + 1, selectedSupplier.indexOf(")"));
            
            ProductDTO productDTO = new ProductDTO();
            productDTO.setSuppCode(supplierCode);
            productDTO.setProdCode(codeText.getText().trim().toUpperCase());
            productDTO.setProdName(nameText.getText().trim());
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDateChooser1.getDate());
            productDTO.setDate(date);
            
            int quantity = Integer.parseInt(quantityText.getText().trim());
            double costPrice = Double.parseDouble(costText.getText().trim());
            double totalCost = quantity * costPrice;
            
            productDTO.setQuantity(quantity);
            productDTO.setTotalCost(totalCost);
            productDTO.setCostPrice(costPrice);
            
            if (!sellText.getText().trim().isEmpty()) {
                productDTO.setSellPrice(Double.parseDouble(sellText.getText().trim()));
            }
            productDTO.setBrand(brandText.getText().trim());
            
            productDAO.addPurchaseDAO(productDTO);
            loadPurchaseData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Purchase transaction completed successfully!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Quantity.");
        }
    }
    
    // Update existing purchase
    private void updatePurchase() {
        if (originalPurchaseID == -1) {
            JOptionPane.showMessageDialog(null, "No purchase selected for update.");
            return;
        }
        
        if (quantityText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Quantity.");
            return;
        }
        
        try {
            ProductDTO productDTO = new ProductDTO();
            productDTO.setPurchaseID(originalPurchaseID);
            productDTO.setProdCode(codeText.getText().trim().toUpperCase());
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDateChooser1.getDate());
            productDTO.setDate(date);
            
            int quantity = Integer.parseInt(quantityText.getText().trim());
            double costPrice = Double.parseDouble(costText.getText().trim());
            double totalCost = quantity * costPrice;
            
            productDTO.setQuantity(quantity);
            productDTO.setTotalCost(totalCost);
            
            productDAO.updatePurchaseDAO(productDTO);
            loadPurchaseData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Purchase updated successfully!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Quantity.");
        }
    }
    
    // Delete purchase
    private void deletePurchase() {
        int selectedRow = purchaseTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a purchase record to delete.");
            return;
        }
        
        int purchaseID = (int) purchaseTable.getValueAt(selectedRow, 0);
        
        int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete purchase record #" + purchaseID + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            productDAO.deletePurchaseDAO(purchaseID);
            loadPurchaseData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Purchase record deleted successfully!");
        }
    }
    
    // Add new supplier button action
    private void btnAddSuppActionPerformed(java.awt.event.ActionEvent evt) {
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        if (dashboard != null) {
            dashboard.addSuppPage();
        } else {
            JOptionPane.showMessageDialog(null, "Please go to Suppliers page to add a new supplier.");
        }
    }
    
    // Refresh data
    private void refreshData() {
        loadSuppliersToCombo();
        loadPurchaseData();
        clearForm();
        JOptionPane.showMessageDialog(null, "Data refreshed!");
    }
    
    // Refresh page data (called from Dashboard)
    public void refreshPageData() {
        loadPurchaseData();
            loadSuppliersToCombo();
        clearForm();
        System.out.println("Purchase page data refreshed");
    }
    
    // Helper method to load purchase details for editing
    private void loadPurchaseDetails(int purchaseID) {
        try {
            ResultSet rs = productDAO.getPurchaseById(purchaseID);
            if (rs != null && rs.next()) {
                // Set quantity
                quantityText.setText(String.valueOf(rs.getInt("quantity")));
                
                // Set date
                String dateStr = rs.getString("date");
                if (dateStr != null && !dateStr.isEmpty()) {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    Date date = dateFormat.parse(dateStr);
                    jDateChooser1.setDate(date);
                }
                rs.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Load suppliers into combo box
    private void loadSuppliersToCombo() {
        try {
            ResultSet rs = supplierDAO.getAllSuppliers();
            suppCombo.removeAllItems();
            suppCombo.addItem("-- Select Supplier --");
            while (rs.next()) {
                suppCombo.addItem(rs.getString("fullname") + " (" + rs.getString("suppliercode") + ")");
            }
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel brandLabe;
    private javax.swing.JTextField brandText;
    private javax.swing.JButton btnAddSupp;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel codeLabel6;
    private javax.swing.JTextField codeText;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costText;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JTable purchaseTable;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityText;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel sellLabel;
    private javax.swing.JTextField sellText;
    private javax.swing.JComboBox<String> suppCombo;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
