/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.UI;

import com.inventory.DAO.ProductDAO;
import com.inventory.DAO.CustomerDAO;
import com.inventory.DTO.ProductDTO;
import com.inventory.DTO.CustomerDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author GKV
 */
public class SalesPage extends javax.swing.JPanel {

    /**
     * Creates new form Products
     */
    
    private ProductDAO productDAO;
    private CustomerDAO customerDAO;
    private String username;  // Add this field
    
    public SalesPage(String username) {
        initComponents();
        productDAO = new ProductDAO();
        customerDAO = new CustomerDAO();
        this.username = username;  // IMPORTANT: Set the username
        loadSalesData();
        setupSearch();
        customizeTable();
        clearForm();
        
        // Add Enter key listeners
        custCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCustomerDetails();
            }
        });
        
        prodCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadProductDetails();
            }
        });
        
        // Add quantity listener to calculate total
        quantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calculateTotal();
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        brandLabe = new javax.swing.JPanel();
        btnAddCust = new javax.swing.JButton();
        codeLabel = new javax.swing.JLabel();
        custCodeText = new javax.swing.JTextField();
        prodCodeText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        quantityText = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        sellText = new javax.swing.JTextField();
        sellLabel = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        prodNameLabel = new javax.swing.JLabel();
        custNameLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1118, 616));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("SALES");

        salesTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(salesTable);

        brandLabe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Sales Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

        btnAddCust.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAddCust.setText("Click to add a New Customer");

        codeLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        codeLabel.setText("Customer Code:");

        custCodeText.addActionListener(this::custCodeTextActionPerformed);

        prodCodeText.addActionListener(this::prodCodeTextActionPerformed);

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Product Code:");

        dateLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dateLabel.setText("Date:");

        quantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityTextKeyReleased(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        quantityLabel.setText("Quantity:");

        sellLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        sellLabel.setText("Selling Price:");

        delButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        delButton.setText("Delete");
        delButton.addActionListener(this::delButtonActionPerformed);

        clearButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        sellButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        sellButton.setText("SELL PRODUCT");
        sellButton.addActionListener(this::sellButtonActionPerformed);

        prodNameLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        prodNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodNameLabel.setText("Product Name Label");

        custNameLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        custNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custNameLabel.setText("Customer Name Label");

        javax.swing.GroupLayout brandLabeLayout = new javax.swing.GroupLayout(brandLabe);
        brandLabe.setLayout(brandLabeLayout);
        brandLabeLayout.setHorizontalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCust, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodCodeText)
                            .addComponent(custCodeText)))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(sellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(custNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        brandLabeLayout.setVerticalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custCodeText)
                    .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCust, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(prodCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellLabel)
                    .addComponent(sellText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        searchLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchLabel.setText("Search: ");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(searchLabel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchField))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custCodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custCodeTextActionPerformed
        loadCustomerDetails();
    }//GEN-LAST:event_custCodeTextActionPerformed

    private void prodCodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCodeTextActionPerformed
        loadProductDetails();
    }//GEN-LAST:event_prodCodeTextActionPerformed

    private void quantityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTextKeyReleased
        calculateTotal();
    }//GEN-LAST:event_quantityTextKeyReleased

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        sellProduct();
    }//GEN-LAST:event_sellButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        deleteSale();
    }//GEN-LAST:event_delButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshData();
    }//GEN-LAST:event_btnRefreshActionPerformed

        // Load customer details when code is entered
    private void loadCustomerDetails() {
        String custCode = custCodeText.getText().trim();
        if (!custCode.isEmpty()) {
            try {
                ResultSet rs = customerDAO.getCustomerByCode(custCode);
                if (rs != null && rs.next()) {
                    String customerName = rs.getString("fullname");
                    String location = rs.getString("location");
                    custNameLabel.setText("Name: " + customerName + " | Location: " + location);
                    rs.close();
                } else {
                    custNameLabel.setText("Name: Not Found | Location: --");
                    JOptionPane.showMessageDialog(null, "Customer not found. Please check the customer code.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            custNameLabel.setText("Name: -- | Location: --");
        }
    }
    
    // Load product details when code is entered
    private void loadProductDetails() {
        String prodCode = prodCodeText.getText().trim();
        if (!prodCode.isEmpty()) {
            try {
                ResultSet rs = productDAO.getProdFromCode(prodCode);
                if (rs != null && rs.next()) {
                    String productName = rs.getString("productname");
                    double sellPrice = rs.getDouble("sellprice");
                    int availableStock = getAvailableStock(prodCode);
                    
                    prodNameLabel.setText("Name: " + productName + " | Available quantity: " + availableStock);
                    sellText.setText(String.format("%.2f", sellPrice));
                    rs.close();
                } else {
                    prodNameLabel.setText("Name: Not Found | Available quantity: 0");
                    sellText.setText("");
                    JOptionPane.showMessageDialog(null, "Product not found. Please check the product code.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            prodNameLabel.setText("Name: -- | Available quantity: --");
            sellText.setText("");
        }
    }
    
    // Get available stock quantity
    private int getAvailableStock(String prodCode) {
        int quantity = 0;
        try {
            ResultSet rs = productDAO.getProdStock();
            while (rs != null && rs.next()) {
                if (rs.getString("productcode").equals(prodCode)) {
                    quantity = rs.getInt("quantity");
                    break;
                }
            }
            if (rs != null) rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return quantity;
    }
    
    // Calculate total revenue
    private void calculateTotal() {
        try {
            int quantity = 0;
            double sellPrice = 0;
            
            if (!quantityText.getText().trim().isEmpty()) {
                quantity = Integer.parseInt(quantityText.getText().trim());
            }
            if (!sellText.getText().trim().isEmpty()) {
                sellPrice = Double.parseDouble(sellText.getText().trim());
            }
            
            double totalRevenue = quantity * sellPrice;
            System.out.println("Total Revenue: " + totalRevenue);
        } catch (NumberFormatException e) {
            // Ignore
        }
    }
    
    // Load sales data into table
    public void loadSalesData() {
        try {
            ResultSet rs = productDAO.getSalesInfo();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"SALES ID", "PRODUCT CODE", "PRODUCT NAME", "QUANTITY", "REVENUE", "SOLD BY"});
            
            if (rs != null) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("salesid"),
                        rs.getString("productcode"),
                        rs.getString("productname"),
                        rs.getInt("quantity"),
                        String.format("%.2f", rs.getDouble("revenue")),
                        rs.getString("sold_by")
                    });
                }
                rs.close();
            }
            salesTable.setModel(model);
            
            if (model.getRowCount() > 0) {
                customizeTable();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading sales data: " + ex.getMessage());
        }
    }
    
    // Search sales records
    private void searchSales() {
        String searchText = searchField.getText().trim();
        
        if (searchText.isEmpty()) {
            loadSalesData();
        } else {
            try {
                ResultSet rs = productDAO.getSalesSearch(searchText);
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new String[]{"SALES ID", "PRODUCT CODE", "PRODUCT NAME", "QUANTITY", "REVENUE", "SOLD BY"});
                
                if (rs != null) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getInt("salesid"),
                            rs.getString("productcode"),
                            rs.getString("productname"),
                            rs.getInt("quantity"),
                            String.format("%.2f", rs.getDouble("revenue")),
                            rs.getString("sold_by")
                        });
                    }
                    rs.close();
                }
                salesTable.setModel(model);
                
                if (model.getRowCount() > 0) {
                    customizeTable();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error searching sales: " + ex.getMessage());
            }
        }
    }
    
    // Setup search functionality
    private void setupSearch() {
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchSales();
            }
        });
    }
    
    // Clear form fields
    public void clearForm() {
        custCodeText.setText("");
        custNameLabel.setText("Name: -- | Location: --");
        prodCodeText.setText("");
        prodNameLabel.setText("Name: -- | Available quantity: --");
        jDateChooser1.setDate(new Date());
        sellText.setText("");
        quantityText.setText("");
        
        salesTable.clearSelection();
    }
    
    // Customize table appearance
    private void customizeTable() {
        try {
            if (salesTable.getColumnCount() == 0) return;
            
            salesTable.getColumnModel().getColumn(0).setPreferredWidth(60);   // ID
            salesTable.getColumnModel().getColumn(1).setPreferredWidth(100);  // Product Code
            salesTable.getColumnModel().getColumn(2).setPreferredWidth(180);  // Product Name
            salesTable.getColumnModel().getColumn(3).setPreferredWidth(80);   // Quantity
            salesTable.getColumnModel().getColumn(4).setPreferredWidth(100);  // Revenue
            salesTable.getColumnModel().getColumn(5).setPreferredWidth(120);  // Sold By
            
            // Center align quantity
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            salesTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
            
            // Right align revenue
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
            salesTable.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            
            salesTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            salesTable.setRowHeight(25);
            
            JTableHeader header = salesTable.getTableHeader();
            header.setFont(new Font("Segoe UI", Font.BOLD, 12));
            header.setBackground(new Color(240, 240, 240));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Sell product
    private void sellProduct() {
        System.out.println("Username being passed to sellProductDAO: " + username);
        if (custCodeText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Customer Code.");
            custCodeText.requestFocus();
            return;
        }
        if (prodCodeText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Product Code.");
            prodCodeText.requestFocus();
            return;
        }
        if (quantityText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Quantity.");
            quantityText.requestFocus();
            return;
        }
        
        try {
            // Get customer code
            String custCode = custCodeText.getText().trim();
            
            // Verify customer exists
            ResultSet custRs = customerDAO.getCustomerByCode(custCode);
            if (!custRs.next()) {
                JOptionPane.showMessageDialog(null, "Customer not found. Please check the customer code.");
                custRs.close();
                return;
            }
            custRs.close();
            
            // Get product code
            String prodCode = prodCodeText.getText().trim();
            
            // Check available stock
            int availableStock = getAvailableStock(prodCode);
            int quantity = Integer.parseInt(quantityText.getText().trim());
            
            if (quantity > availableStock) {
                JOptionPane.showMessageDialog(null, "Insufficient stock! Available quantity: " + availableStock);
                return;
            }
            
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(null, "Please enter a valid quantity.");
                return;
            }
            
            double sellPrice = Double.parseDouble(sellText.getText().trim());
            double totalRevenue = quantity * sellPrice;
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDateChooser1.getDate());
            
            ProductDTO productDTO = new ProductDTO();
            productDTO.setCustCode(custCode);
            productDTO.setProdCode(prodCode);
            productDTO.setDate(date);
            productDTO.setQuantity(quantity);
            productDTO.setTotalRevenue(totalRevenue);
            
            productDAO.sellProductDAO(productDTO, username);
            loadSalesData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Product sold successfully!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numbers for Quantity.");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error processing sale: " + e.getMessage());
        }
    }
    
    // Delete sale record
    private void deleteSale() {
        int selectedRow = salesTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a sale record to delete.");
            return;
        }
        
        int saleID = (int) salesTable.getValueAt(selectedRow, 0);
        
        int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete sale record #" + saleID + "?\nThis will also restore the stock quantity.",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            productDAO.deleteSaleDAO(saleID);
            loadSalesData();
            clearForm();
            JOptionPane.showMessageDialog(null, "Sale record deleted successfully!");
        }
    }
    
    // Add new customer button action
    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        if (dashboard != null) {
            dashboard.addCustPage();
        } else {
            JOptionPane.showMessageDialog(null, "Please go to Customers page to add a new customer.");
        }
    }
    
    // Refresh data
    private void refreshData() {
        loadSalesData();
        clearForm();
        JOptionPane.showMessageDialog(null, "Data refreshed!");
    }
    
    // Refresh page data (called from Dashboard)
    public void refreshPageData() {
        loadSalesData();
        clearForm();
        System.out.println("Sales page data refreshed");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brandLabe;
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField custCodeText;
    private javax.swing.JLabel custNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton delButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField prodCodeText;
    private javax.swing.JLabel prodNameLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityText;
    private javax.swing.JTable salesTable;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton sellButton;
    private javax.swing.JLabel sellLabel;
    private javax.swing.JTextField sellText;
    // End of variables declaration//GEN-END:variables
}
