/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.UI;

import com.inventory.DAO.UserDAO;
import com.inventory.DTO.UserDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author GKV
 */
public class UsersPage extends javax.swing.JPanel {

    /**
     * Creates new form Products
     */
    private UserDAO userDAO;  // Single instance
    private boolean isEditMode = false;
    private String originalUsername = null;
    
    public UsersPage() {
        initComponents();
        userDAO = new UserDAO();  // Create once
        loadDataSet();
        setupSearch();
        customizeTable();
        clearForm();
        updateButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        brandLabe = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        locationText = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        debitAmountLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        creditAmountLabel = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        userTypeComboBox = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1118, 616));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("USERS");

        userTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        brandLabe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nameLabel.setText("Full Name:");

        locationLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        locationLabel.setText("Location:");

        contactLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contactLabel.setText("Contact#:");

        debitAmountLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        debitAmountLabel.setText("Username:");

        addButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(this::addButtonActionPerformed);

        creditAmountLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        creditAmountLabel.setText("Password:");

        delButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        delButton.setText("Delete");
        delButton.addActionListener(this::delButtonActionPerformed);

        updateButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Employee" }));

        clearButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        javax.swing.GroupLayout brandLabeLayout = new javax.swing.GroupLayout(brandLabe);
        brandLabe.setLayout(brandLabeLayout);
        brandLabeLayout.setHorizontalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandLabeLayout.createSequentialGroup()
                        .addComponent(debitAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(creditAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordText))
                    .addGroup(brandLabeLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        brandLabeLayout.setVerticalGroup(
            brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandLabeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debitAmountLabel)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditAmountLabel)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(brandLabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(this::refreshButtonActionPerformed);

        searchLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchLabel.setText("Search: ");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(searchLabel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchField))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(brandLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        int row = userTable.getSelectedRow();
        if (row >= 0) {
            originalUsername = userTable.getValueAt(row, 0).toString();
            usernameText.setText(originalUsername);
            usernameText.setEnabled(true);  // Allow editing
            nameText.setText(userTable.getValueAt(row, 1).toString());
            locationText.setText(userTable.getValueAt(row, 2).toString());
            contactText.setText(userTable.getValueAt(row, 3).toString());
            
            String userType = userTable.getValueAt(row, 4).toString();
            if (userType.equalsIgnoreCase("ADMINISTRATOR")) {
                userTypeComboBox.setSelectedIndex(0);
            } else {
                userTypeComboBox.setSelectedIndex(1);
            }
            
            passwordText.setText("");  // Clear password field for security
            
            isEditMode = true;
            updateButton.setEnabled(true);
            addButton.setEnabled(true);
        }      
    }//GEN-LAST:event_userTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addUser(); 
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateUser();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        deleteUser();
    }//GEN-LAST:event_delButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refreshData();
    }//GEN-LAST:event_refreshButtonActionPerformed
    
        // Load users data into table
    public void loadDataSet() {
        try {
            ResultSet rs = userDAO.getQueryResult();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"USERNAME", "FULL NAME", "LOCATION", "CONTACT", "USER TYPE"});
            
            if (rs != null) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("username"),
                        rs.getString("fullname"),
                        rs.getString("location"),
                        rs.getString("phone"),
                        rs.getString("usertype")
                    });
                }
                rs.close();
            }
            userTable.setModel(model);
            
            if (model.getRowCount() > 0) {
                customizeTable();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading users: " + ex.getMessage());
            userTable.setModel(new DefaultTableModel());
        }
    }
    
    // Search users
    private void searchUsers() {
        String searchText = searchField.getText().trim();
        
        if (searchText.isEmpty()) {
            loadDataSet();
        } else {
            try {
                ResultSet rs = userDAO.searchUsers(searchText);
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new String[]{"USERNAME", "FULL NAME", "LOCATION", "CONTACT", "USER TYPE"});
                
                if (rs != null) {
                    while (rs.next()) {
                        model.addRow(new Object[]{
                            rs.getString("username"),
                            rs.getString("fullname"),
                            rs.getString("location"),
                            rs.getString("phone"),
                            rs.getString("usertype")
                        });
                    }
                    rs.close();
                }
                userTable.setModel(model);
                
                if (model.getRowCount() > 0) {
                    customizeTable();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    // Setup search functionality
    private void setupSearch() {
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchUsers();
            }
        });
    }
    
    // Clear form fields
    public void clearForm() {
        nameText.setText("");
        locationText.setText("");
        contactText.setText("");
        usernameText.setText("");
        passwordText.setText("");
        userTypeComboBox.setSelectedIndex(0);
        
        isEditMode = false;
        originalUsername = null;
        updateButton.setEnabled(false);
        addButton.setEnabled(true);
        usernameText.setEnabled(true);
        userTable.clearSelection();
    }
    
    // Customize table appearance
    private void customizeTable() {
        try {
            if (userTable.getColumnCount() == 0) return;
            
            userTable.getColumnModel().getColumn(0).setPreferredWidth(100);  // Username
            userTable.getColumnModel().getColumn(1).setPreferredWidth(180);  // Full Name
            userTable.getColumnModel().getColumn(2).setPreferredWidth(120);  // Location
            userTable.getColumnModel().getColumn(3).setPreferredWidth(100);  // Contact
            userTable.getColumnModel().getColumn(4).setPreferredWidth(100);  // User Type
            
            userTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            userTable.setRowHeight(25);
            
            JTableHeader header = userTable.getTableHeader();
            header.setFont(new Font("Segoe UI", Font.BOLD, 12));
            header.setBackground(new Color(240, 240, 240));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Add new user
    private void addUser() {
        if (nameText.getText().trim().isEmpty() ||
            locationText.getText().trim().isEmpty() ||
            contactText.getText().trim().isEmpty() ||
            usernameText.getText().trim().isEmpty() ||
            passwordText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all required fields.");
            return;
        }
        
        UserDTO userDTO = new UserDTO();
        String userType = ((String) userTypeComboBox.getSelectedItem()).toUpperCase();
        userDTO.setFullName(nameText.getText().trim());
        userDTO.setLocation(locationText.getText().trim());
        userDTO.setPhone(contactText.getText().trim());
        userDTO.setUsername(usernameText.getText().trim());
        userDTO.setPassword(passwordText.getText().trim());
        userDTO.setUserType(userType);
        
        userDAO.addUserDAO(userDTO, userType);
        loadDataSet();
        clearForm();
        JOptionPane.showMessageDialog(null, "User added successfully!");
    }
    
    // Update existing user
    private void updateUser() {
        if (originalUsername == null) {
            JOptionPane.showMessageDialog(null, "No user selected for update.");
            return;
        }
        
        if (nameText.getText().trim().isEmpty() ||
            locationText.getText().trim().isEmpty() ||
            contactText.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all required fields.");
            return;
        }
        
        String newUsername = usernameText.getText().trim();
        String userType = ((String) userTypeComboBox.getSelectedItem()).toUpperCase();
        
        UserDTO userDTO = new UserDTO();
        userDTO.setFullName(nameText.getText().trim());
        userDTO.setLocation(locationText.getText().trim());
        userDTO.setPhone(contactText.getText().trim());
        userDTO.setUsername(newUsername);
        userDTO.setUserType(userType);
        
        // If password is provided, update it
        if (!passwordText.getText().trim().isEmpty()) {
            userDTO.setPassword(passwordText.getText().trim());
            userDAO.updateUserWithPassword(userDTO, originalUsername);
        } else {
            userDAO.updateUser(userDTO, originalUsername);
        }
        
        loadDataSet();
        clearForm();
        JOptionPane.showMessageDialog(null, "User updated successfully!");
    }
    
    // Delete user
    private void deleteUser() {
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a user to delete.");
            return;
        }
        
        String username = userTable.getValueAt(selectedRow, 0).toString();
        
        int confirm = JOptionPane.showConfirmDialog(null,
            "Are you sure you want to delete user: " + username + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            userDAO.deleteUserDAO(username);
            loadDataSet();
            clearForm();
            JOptionPane.showMessageDialog(null, "User deleted successfully!");
        }
    }
    
    // Refresh data
    private void refreshData() {
        loadDataSet();
        clearForm();
        JOptionPane.showMessageDialog(null, "Data refreshed!");
    }
    
    // Refresh page data (called from Dashboard)
    public void refreshPageData() {
        loadDataSet();
        clearForm();
        System.out.println("Users page data refreshed");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel brandLabe;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactText;
    private javax.swing.JLabel creditAmountLabel;
    private javax.swing.JLabel debitAmountLabel;
    private javax.swing.JButton delButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable userTable;
    private javax.swing.JComboBox<String> userTypeComboBox;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
   
}
